services:
  - type: web
    name: lnd-pure-duckduckgo-scraper-optimized
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --bind 0.0.0.0:$PORT app:app --timeout 180 --workers 1 --keep-alive 2 --max-requests 1000 --max-requests-jitter 50
    healthCheckPath: /api/health
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.4
      - key: RENDER_EXTERNAL_URL
        generateValue: true

