services:
  - type: web
    name: lnd-duckduckgo-cloudflare-dns-scraper
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --bind 0.0.0.0:$PORT app:app --timeout 200 --workers 1 --keep-alive 3 --max-requests 1200 --max-requests-jitter 100
    healthCheckPath: /api/health
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.4
      - key: RENDER_EXTERNAL_URL
        generateValue: true

